name: PNPM publish
on:
    release:
        types: [published]
env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store

jobs:
    release:
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install pnpm
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Setup npmrc
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            - name: setup pnpm config
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER

            - name: Install
              run: pnpm install
            # set up git since we will later push to the repo

            - run: git config --global user.name "GitHub CD bot"
            - run: git config --global user.email "dmitrii@moralis.io"
            # upgrade npm version in package.json to the tag used in the release.
            # - run: npm version --force ${{ github.event.release.tag_name }}
            # build the project
            - name: Build
              run: pnpm run build
            # run tests just in case
            - name: Test
              run: pnpm vitest --run

            - name: Enter Alpha
              if: 'github.event.release.prerelease'
              run: pnpm changeset pre enter alpha

            - name: create and publish versions
              uses: changesets/action@v1
              with:
                  version: pnpm ci:version
                  commit: 'chore: update versions'
                  title: 'chore: update versions'
                  publish: pnpm ci:release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Exit Alpha
              if: 'github.event.release.prerelease'
              run: pnpm changeset pre exit
